version: '3'
services:
  frontmen_database:
    image: mariadb:10.3.4
    container_name: frontmen-boilerplate-v1-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_frontmen_boilerplate_v1_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - frontmen
volumes:
  db_frontmen_boilerplate_v1_data:
networks:
  frontmen: